name = "moji-diary"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "moji-diary-db"
database_id = "5ee"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "moji-diary-media"
